# dbtk sample configuration file
# Copy to ~/.config/dbtk.yml and customize

settings:
  default_batch_size: 1000
  default_column_case: lower
  default_country: US
  default_header_clean: 2  # Clean.LOWER_NOSPACE
  default_timezone: UTC

  # Logging configuration for integration scripts
  logging:
    directory: ./logs                  # Directory for log files
    level: INFO                         # DEBUG, INFO, WARNING, ERROR, CRITICAL
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    timestamp_format: '%Y-%m-%d %H:%M:%S'  # Format for timestamps in log messages
    filename_format: '%Y%m%d_%H%M%S'   # Timestamp format for log filenames
                                        # Set to '%Y%m%d' for one log per day
                                        # Set to '' for single rolling log file (no timestamp)
    split_errors: true                  # Create separate _error.log file for errors
    console: true                       # Also output to console
    retention_days: 30                  # Days to keep old log files (for cleanup_old_logs)

connections:
  # Example connection configurations
  dev_postgres:
    driver: psycopg    # Optional, psycopg2 has the highest priority, this will ensure psycopg(3) is used if both are installed
    type: postgres     # type is optional IF you specify a driver
    host: localhost
    port: 5432
    database: myapp_dev
    user: developer
    cursor:                 # These settings will be passed down when creating a cursor
      type: dict
      batch_size: 4000
      column_case: preserve
      debug: False
      return_cursor: True
    # password: prompt  # Will prompt for password
    # encrypted_password: gAAAAABh...  # Or use encrypted

  prod_oracle:
    type: oracle
    host: oracle.company.com
    port: 1521
    database: prod.company.com
    user: app_user
    encrypted_password: gAAAAABh...

  imdb_odbc_dsn:
    driver: pyodbc_postgres
    dsn: IMDB_PG  # user or system DSN
    password: '${IMDB_USER_PASS}'    # Pull from environment variable

  imdb_odbc:
    driver: pyodbc_postgres
    host: localhost
    port: 5432
    database: imdb
    user: imdb_user
    encrypted_password: gAAAAABh...

  sqlserver_dev:
    driver: pyodbc_sqlserver
    type: sqlserver
    host: localhost\SQLEXPRESS  # Use instance name if applicable
    port: 1433
    database: myapp_dev
    user: dev_user
    password: prompt
    cursor:
      fast_executemany: true  # Recommended for bulk operations; disable if using TEXT/NVARCHAR(MAX)/JSON columns

# Encrypted passwords (optional)
passwords:
  openai_key:
    description: "OpenAI API key for data processing"
    encrypted_password: gAAAAABh...

# Custom driver definitions (optional)
drivers:
  firbird:
    database_type: firebird
    module: firebird.driver # only required if name (firbird) does not mactch module (import) name
    priority: 1
    param_map: { }  # if driver does not use standard names (user, password, host, port, database) map them here
    required_params: [ { 'host', 'database', 'user' }, { 'dsn' } ]
    optional_params: { 'port', 'password' }
    connection_method: kwargs
    default_port: 3050